include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - build/**
  enable-experiment:
    - records
    - patterns
    - sealed-class
    - class-modifiers
linter:
  rules:
    file_names: false
