name: rive_livestream_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0-189.0.dev <4.0.0'

dependencies:
  dart_frog: ^0.3.0
  dart_frog_web_socket: ^0.1.0-dev.3
  common_repository:
    path: ../packages/common_repository
  broadcast_bloc: ^0.1.0-dev.2
  stream_channel: ^2.1.1

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  flutter_lints: ^2.0.0
