name: common_repository
description: Dart package which manages shared code between repositories
publish_to: none

environment:
  sdk: '>=3.0.0-417.4.beta <4.0.0'

dev_dependencies:
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
